### ISSUE TITLE
Consider moving Julia download away from LazyArtifacts

### ISSUE THREAD

**Issue by miguelbiron** [roualdes/bridgestan#226]
Hi -- just ran into this weird bug where an error is raised on Julia 1.10 while downloading bridgestan artifact inside a github CI Windows runner

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/8636249839/job/23678766648#step:8:1159

Interestingly this doesn't happen on Julia 1.9

https://github.com/Julia-Tempering/Pigeons.jl/actions/runs/8636249839/job/23678765917#step:8:1136

**Comment by WardBrian** [comment]
Definitely weird! 

Our CI wouldn't catch this because we only test that the download succeeds, not the permissions of the files, but it sounds like this is a Julia 1.10 regression: https://github.com/JuliaLang/julia/issues/52272

Maybe us putting something we want write access to into the artifacts directory is bad manners, I'm not sure. If so we could switch to what we do in Python etc and put it under ~/.bridgestan

@sethaxen originally added this feature for us so I'm going to ping him to see if he has any thoughts

**Comment by miguelbiron** [comment]
Ah! Nice find, it didn't occur to me that this would be affecting other packages... it definitely looks an important regression on Julia 1.10. Will keep digging to see if there's anything I can do on my end, thank you.

**Comment by WardBrian** [comment]
I got confirmation that we probably shouldn't be using the artifacts system for this: https://github.com/JuliaLang/julia/issues/52272#issuecomment-2050516371

They recommended https://github.com/JuliaPackaging/Scratch.jl, which seems similar, but I'm leaning toward using `~/.bridgestan` like we do in Python or R. Thoughts @roualdes @sethaxen?

**Comment by roualdes** [comment]
I vote to just use `~/.bridgestan` instead of Scratch.jl, lest we find later on some unknown unknowns about Scratch.jl and its personal philosophies.  We theoretically know a lot about using `~/.bridgstan` across various machines.
