### ISSUE TITLE
Moving from gitlab to github

### ISSUE THREAD

**Issue by goedman** [roualdes/bridgestan#24]
Hi @roualdes 

Need to make still one minor change to StanSample.jl but I'm wondering if below function can be much simpler:
```
function sim(smb::BridgeStan.StanModel, x=LinRange(0.1, 0.9, 100))
        q = zeros(length(x))
        ld = zeros(length(x))
        g = zeros(length(x))
        for (i, p) in enumerate(x)
            q[i] = @. log(x[]i / (1 - x[i]))        # unconstrained scale
            lp, grad = BridgeStan.log_density_gradient(smb, [q[i]], jacobian = 0)
            ld[i] = lp[1]
            g[i] = grad[1]
        end
        return DataFrame(x=x, q=q, log_density=ld, gradient=g)
    end
```
It feels like I'm doing something wrong in the call to log_density_gradient.

I was hoping for (and tried variations on) something like:
```
function sim(smb::BridgeStan.StanModel, x=LinRange(0.1, 0.9, 100))
    q = @. log(x / (1 - x))        # unconstrained scale
    lp, grad = BridgeStan.log_density_gradient(smb, q, jacobian = 0) # or a broadcasted version
    return DataFrame(x=x, q=q, log_density=ld, gradient=g)
end
```

**Comment by roualdes** [comment]
So you're trying to evaluate the log density and gradient of a batch of values `x`?  

For now, BridgeStan users are in charge of their own batch evaluations.  And it will necessarily be fiddly like this.

However, the current strategy won't extend to more complicated Stan programs.  It only works here, because ld and g both return vectors of length 1.  But for a Stan program where q has length greater than 1, then g will have length greater than 1, but ld will remain with length equal to 1, so the returned data frame will be malformed.

Maybe if I understood the context in which you imagine the function `smb` being used, I could offer more tips.

**Comment by goedman** [comment]
Yes, this sim function is only used in an example, not part of StanSample.jl. In case g has a length > 1 I would probably opt for a DataFrame with a nested column.

I used this sim function simply to plot ld and g as a function of x. 

But I see your point and certainly can live with it! Thanks for your help.

**Comment by roualdes** [comment]
I think you could use `log_density_gradient!()` ([doc](https://roualdes.github.io/bridgestan/languages/julia.html#BridgeStan.log_density_gradient!)) inside the for loop as

```
ld[i] = BridgeStan.log_density_gradient!(smb, q[i:i], g[i:i], jacobian = 0)
```
which cleans up the loop some.  

Would you mind closing this issue if the situation is adequate?

**Comment by goedman** [comment]
Thank you, that looks way better!
