### ISSUE TITLE
Code example for Stan + JAX via BridgeStan

### ISSUE THREAD

**Issue by gil2rok** [roualdes/bridgestan#240]
I made a minimal code example that allows JAX to access Stan models via BridgeStan [here](https://github.com/gil2rok/jax-stan/tree/main).

I discussed with @roualdes and we thought it might be helpful for others to see this as well.

Please let me know if you've any questions or code improvements.

**Comment by WardBrian** [comment]
Similar to the code @justindomke and I wrote last spring: https://github.com/WardBrian/bridgestan/blob/examples/blackjax/python/blackjax_example.py
but I think yours is a bit nicer by defining the ShapeDtypeStructs and not setting Jax to fully use float64

Otherwise the main differences are if you also want to vmap over the constrain function

**Comment by gil2rok** [comment]
Haha nice!

It's good to have a couple examples of these floating around.
