### ISSUE TITLE
add function to return CmdStan and Stan version numbers

### ISSUE THREAD

**Issue by bob-carpenter** [roualdes/bridgestan#40]
We should have a way from within BridgeStan to report which version of CmdStan and which version of Stan it's using.  

For CmdStan, we can get it from the makefile in CmdStan from the home directory:

```
make print-CMDSTAN_VERSION
```

For Stan, it's available as a three C++ constants.

**Comment by bob-carpenter** [comment]
I can add a function to get the Stan version.  Do you think it should return a triple of major/minor/patch or just a number?

**Comment by WardBrian** [comment]
I think it's best to return a string of "major.minor.patch".

Do we want to have a function specifically for the version? I think ultimately the following would be useful:

1. Version (major.minor.patch)
2. What Stan defines were used (see `cmdstan/src/cmdstan/write_stan_flags.hpp` for a similar idea)
3. What Stanc version and flags were used (Available as `model_->model_compile_info()`).


To me it would make sense to have all of this output by the same function called something like `model_info()` rather than splitting it up

**Comment by WardBrian** [comment]
For example, I think it's reasonable for this method to output a string like:

```
Stan version: 2.30.0
Stan C++ Defines:
        STAN_THREADS=false
        STAN_MPI=false
        STAN_OPENCL=false
        STAN_NO_RANGE_CHECKS=false
        STAN_CPP_OPTIMS=false
Stan Compiler Details:
        stanc_version = stanc3 v2.30.1
        stancflags = 
```

I think the code to do this is pretty simple
