### ISSUE TITLE
Warn users if they have many copies of bridgestan

### ISSUE THREAD

**Issue by WardBrian** [roualdes/bridgestan#83]
See https://github.com/roualdes/bridgestan/pull/80#issuecomment-1464645491 and discussion:

In both Python and Julia, a user could eventually end up with many downloaded copies due to version bumps over time. For Python, this is easy to detect as they will be in `~/.bridgestan/bridgestan-VERSION`. In Julia, it is more difficult, since they will live under `~/.julia/artifacts` as git-tree-hashes, not useful names.

**Comment by sethaxen** [comment]
In Julia this should not be necessary, as artifacts are automatically garbage collected after a grace period of nonuse.

**Comment by WardBrian** [comment]
Very cool, thanks for letting us know about that!

**Comment by mjhajharia** [comment]
> See [#80 (comment)](https://github.com/roualdes/bridgestan/pull/80#issuecomment-1464645491) and discussion:
> 
> In both Python and Julia, a user could eventually end up with many downloaded copies due to version bumps over time. For Python, this is easy to detect as they will be in `~/.bridgestan/bridgestan-VERSION`. In Julia, it is more difficult, since they will live under `~/.julia/artifacts` as git-tree-hashes, not useful names.

+1 

On a related note, something similar happened to me this week(I had the repository cloned in my own directory structure, and I usually manually set the path everytime, but then at some point I messed up by doing a PyPi install as well), so I do think a warning would be very nice.

And about Julia, I'm not very sure, so please correct me if I'm missing something, I ended up in this situation where I had different versions of bridgestan cloned locally on different devices, and I was syncing the same `.toml` for reproducibility, which again lead to a bunch of issues.

I think most of the problems are owed to installing bridgestan yourself as well as using pypi or add package in julia, so you end up with two local clones in different places. Not sure if this is helpful for developers, because I could've avoided this by being more careful.
